//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by WECompressor.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_ABOUTBOXOLD                 102
#define IDR_MAINFRAME                   103
#define IDD_WECOMPRESSOR_DIALOG         104
#define IDD_SCROLLBITMAP_DIALOG         105
#define IDD_WECOMPRESSOR_TAB1           106
#define IDD_WECOMPRESSOR_TAB2           107
#define IDD_WECOMPRESSOR_TAB3           108
#define IDB_LOGO                        108
#define IDB_LOGO_WENDETTA               109
#define IDS_HELP_WECOMPRESSOR           109
#define IDI_PP_ATTENTION                110
#define IDS_IMAGETABCOL2                110
#define IDI_PP_INFORMATION              111
#define IDS_IMAGETABCOL3                111
#define IDI_PP_QUESTION                 112
#define IDS_IMAGETABCOL4                112
#define IDI_VIEWFILE                    113
#define IDS_IMAGETABCOL5                113
#define IDI_SELFILE                     114
#define IDS_IMAGETABCOL6                114
#define IDS_IMAGETABCOL7                115
#define IDS_IMAGETABCOL8                116
#define IDS_PALTABCOL2                  117
#define IDS_PALTABCOL3                  118
#define IDS_PALTABCOL4                  119
#define IDS_PALTABCOL5                  120
#define IDS_PALTABCOL6                  121
#define IDS_PALTABCOL7                  122
#define IDS_PALTABCOL8                  123
#define IDS_PALTABCOL9                  124
#define IDS_FILTER_ALL                  125
#define IDS_FILTER_BIN                  126
#define IDS_FILTER_BINCOMPR             127
#define IDS_FILTER_BMP                  128
#define IDS_FILTER_CLU                  129
#define IDS_FILTER_PAL                  130
#define IDS_FILTER_RAW                  131
#define IDS_FILTER_SRC                  132
#define IDS_FILTER_TEX                  133
#define IDS_FILTER_TIM                  134
#define IDS_FILTER_TXT                  135
#define IDS_NAME_NOFILE                 136
#define IDS_TITLE_IMAGE                 137
#define IDS_TITLE_PALETTE               138
#define IDS_TITLE_COLORS                139
#define IDS_BUTTON_TAB2_INSERTFILE      140
#define IDS_BUTTON_TAB2_MAKEFILE        141
#define IDS_HELP_EXIT                   142
#define IDS_HELP_IMAGE_X                143
#define IDS_HELP_IMAGE_Y                144
#define IDS_HELP_INFO                   145
#define IDS_HELP_INFORMATION_TITLE      146
#define IDS_HELP_MANUAL_IMAGE           147
#define IDS_HELP_MANUAL_PAL             148
#define IDS_HELP_OFFSET_IMAGE           149
#define IDS_HELP_OFFSET_PAL             150
#define IDS_HELP_TAB1_MAKEFILE          151
#define IDS_HELP_TAB1_SELBUTTON         152
#define IDS_HELP_TAB1_SELBUTTON2        153
#define IDS_HELP_TAB1_SELBUTTON3        154
#define IDS_HELP_TAB1_SELBUTTON3B       155
#define IDS_HELP_TAB1_SELBUTTON3C       156
#define IDS_HELP_TAB1_SELBUTTON3D       157
#define IDS_HELP_TAB1_SELBUTTON3D2      158
#define IDS_HELP_TAB1_SELBUTTON3E       159
#define IDS_HELP_TAB1_SELBUTTON4        160
#define IDS_HELP_TAB1_SELFILE           161
#define IDS_HELP_TAB1_SELGAME           162
#define IDS_HELP_TAB1_TEXSHIRT          163
#define IDS_HELP_TAB1_VIEW              164
#define IDS_HELP_TAB2_ADVANCED          165
#define IDS_HELP_TAB2_AUTOPAL           166
#define IDS_HELP_TAB2_INSERTFILE        167
#define IDS_HELP_TAB2_MAKEFILE          168
#define IDS_HELP_TAB2_SELBUTTON         169
#define IDS_HELP_TAB2_SELBUTTON2        170
#define IDS_HELP_TAB2_SELBUTTON2B       171
#define IDS_HELP_TAB2_SELBUTTON3        172
#define IDS_HELP_TAB2_SELBUTTON3B       173
#define IDS_HELP_TAB2_SELBUTTON4        174
#define IDS_HELP_TAB2_SELBUTTON4B       175
#define IDS_HELP_TAB2_SELBUTTONB        176
#define IDS_HELP_TAB2_SELBUTTONC        177
#define IDS_HELP_TAB2_SELFILE           178
#define IDS_HELP_TAB2_SELPAL            179
#define IDS_HELP_TAB2_VIEW              180
#define IDS_HELP_TAB3_256X128MODE       181
#define IDS_HELP_TAB3_EXTRACTTEX        182
#define IDS_HELP_TAB3_MAKETEX           183
#define IDS_HELP_TAB3_SELAUTO           184
#define IDS_HELP_TAB3_SELAUTOFLAG       185
#define IDS_HELP_TAB3_SELBUTTON         186
#define IDS_HELP_TAB3_SELBUTTON2        187
#define IDS_HELP_TAB3_SELBUTTON2B       188
#define IDS_HELP_TAB3_SELBUTTON3        189
#define IDS_HELP_TAB3_SELBUTTON4        190
#define IDS_HELP_TAB3_SELBUTTON5        191
#define IDS_HELP_TAB3_SELBUTTON6        192
#define IDS_HELP_TAB3_SELBUTTON7        193
#define IDS_HELP_TAB3_SELBUTTON8        194
#define IDS_HELP_TAB3_SELBUTTON8B       195
#define IDS_HELP_TAB3_SELBUTTON9        196
#define IDS_HELP_TAB3_SELBUTTON10       197
#define IDS_HELP_TAB3_SELBUTTON11       198
#define IDS_HELP_TAB3_SELBUTTON12       199
#define IDS_HELP_TAB3_SELFILE           200
#define IDS_HELP_TAB3_SELPAL            201
#define IDS_HELP_TAB3_VIEWBUTTON        202
#define IDS_HELP_COMBO_PAL              203
#define IDS_INFO_ALLOK                  204
#define IDS_INFO_BMPOK                  205
#define IDS_INFO_CREATEDIR              206
#define IDS_INFO_EXTRACTTEX_OK          207
#define IDS_INFO_IMAGES_FOUND           208
#define IDS_INFO_INSERTBIN_OK           209
#define IDS_INFO_INSERTBLOCK1           210
#define IDS_INFO_INSERTBLOCK2           211
#define IDS_INFO_INSERTBLOCK_NO         212
#define IDS_INFO_INSERTBLOCK_YES        213
#define IDS_INFO_MAKEBIN_OK             214
#define IDS_INFO_MAKETEX_OK             215
#define IDS_INFO_NO_IMAGES_FOUND        216
#define IDS_INFO_NO_PALETTES_FOUND      217
#define IDS_INFO_PALETTES_FOUND         218
#define IDS_INFO_RAWOK                  219
#define IDS_INFO_TAB1_NEWALL            220
#define IDS_INFO_TAB1_NEWBMP            221
#define IDS_INFO_TAB1_NEWRAW            222
#define IDS_INFO_TAB1_NEWTIM            223
#define IDS_INFO_TAB1_NEWTXT            224
#define IDS_INFO_TAB1_OPENIMAGE         225
#define IDS_INFO_TAB1_OPENPALETTE       226
#define IDS_INFO_TAB2_NEWBIN            227
#define IDS_INFO_TAB2_NEWPAL            228
#define IDS_INFO_TAB2_OPENBMP           229
#define IDS_INFO_TAB2_OPENCLUT          230
#define IDS_INFO_TAB2_OPENIMAGE         231
#define IDS_INFO_TAB2_OPENPAL           232
#define IDS_INFO_TAB2_OPENPALETTE       233
#define IDS_INFO_TAB2_OPENRAW           234
#define IDS_INFO_TAB2_OPENTIM           235
#define IDS_INFO_TAB2_PALETTE1          236
#define IDS_INFO_TAB2_PALETTE2          237
#define IDS_INFO_TAB2_TITLE1            238
#define IDS_INFO_TAB2_TITLE2            239
#define IDS_INFO_TAB3_NEWTEX            240
#define IDS_INFO_TAB3_OPENFLAG          241
#define IDS_INFO_TAB3_OPENFLAGPAL       242
#define IDS_INFO_TAB3_OPENPALGIOC1      243
#define IDS_INFO_TAB3_OPENPALGIOC2      244
#define IDS_INFO_TAB3_OPENPALPORT1      245
#define IDS_INFO_TAB3_OPENPALPORT2      246
#define IDS_INFO_TAB3_OPENREFREE        247
#define IDS_INFO_TAB3_OPENTEX           248
#define IDS_INFO_TAB3_OPENTEXGIOC1      249
#define IDS_INFO_TAB3_OPENTEXGIOC2      250
#define IDS_INFO_TAB3_OPENTEXMAN1       251
#define IDS_INFO_TAB3_OPENTEXMAN2       252
#define IDS_INFO_TAB3_TITLE1            253
#define IDS_INFO_TAB3_TITLE2            254
#define IDS_INFO_TIMOK                  255
#define IDS_INFO_TXTOK                  256
#define IDS_INFO_TXT_GRAPHICS           257
#define IDS_INFO_TXT_PALETTES           258
#define IDS_ERROR_MESSAGEBOX            259
#define IDS_ERROR_TAB1_ALL              260
#define IDS_ERROR_TAB1_BMP              261
#define IDS_ERROR_TAB1_RAW              262
#define IDS_ERROR_TAB1_TIM              263
#define IDS_ERROR_TAB1_TXT              264
#define IDS_ERROR_TAB2_INSERTBIN        265
#define IDS_ERROR_TAB2_MAKEBIN          266
#define IDS_ERROR_TAB3_EXTRACTTEX       267
#define IDS_ERROR_TAB3_MAKETEX          268
#define IDS_ERROR_TAB_LENGTH            269
#define IDS_HELP_TAB_IMAGEPAL           270
#define IDB_LOGO_CARP                   271
#define ID_INFO                         1000
#define IDC_256X128MODE                 1001
#define IDC_ADVANCED                    1002
#define IDC_AUTOPALTEXT1                1003
#define IDC_AUTOPALTEXT2                1004
#define IDC_BUTTON_EXTRACTTEX           1005
#define IDC_BUTTON_MAKEFILE             1006
#define IDC_BUTTON_MAKETEX              1007
#define IDC_BUTTON_VIEWIMAGE            1008
#define IDC_CHECK_AUTOPAL               1009
#define IDC_COMBO_PALETTE               1010
#define IDC_COMBO_SELAUTOFLAG           1011
#define IDC_COMBO_SELAUTOGIO1           1012
#define IDC_COMBO_SELAUTOGIO2           1013
#define IDC_COMBO_SELAUTOMAN1           1014
#define IDC_COMBO_SELAUTOMAN2           1015
#define IDC_COMBO_SELFILE               1016
#define IDC_COMBO_SELGAME               1017
#define IDC_COMBO_SELPAL                1018
#define IDC_COMBO_SELPALFLAG            1019
#define IDC_COMBO_SELPALGIOC1           1020
#define IDC_COMBO_SELPALGIOC2           1021
#define IDC_COMBO_SELPALPORT1           1022
#define IDC_COMBO_SELPALPORT2           1023
#define IDC_COMBO_SELTEXGIO1            1024
#define IDC_COMBO_SELTEXGIO2            1025
#define IDC_COMBO_SELTEXMAN1            1026
#define IDC_COMBO_SELTEXMAN2            1027
#define IDC_COMBO_SELTEXREFREE          1028
#define IDC_COMBO_SELTEXTIFO            1029
#define IDC_EDIT_OFFSET_IMAGES          1030
#define IDC_EDIT_OFFSET_PAL             1031
#define IDC_EDIT_X                      1032
#define IDC_EDIT_Y                      1033
#define IDC_FILE_IMAGE                  1034
#define IDC_FILE_NEWTEX                 1035
#define IDC_FILE_PALETTE                1036
#define IDC_FILE_PALFLAG                1037
#define IDC_FILE_PALGIOC1               1038
#define IDC_FILE_PALGIOC2               1039
#define IDC_FILE_PALPORT1               1040
#define IDC_FILE_PALPORT2               1041
#define IDC_FILE_READIMAGE              1042
#define IDC_FILE_READPAL                1043
#define IDC_FILE_TEXFLAG                1044
#define IDC_FILE_TEXGIOC1               1045
#define IDC_FILE_TEXGIOC2               1046
#define IDC_FILE_TEXMANLUN1             1047
#define IDC_FILE_TEXMANLUN2             1048
#define IDC_FILE_TEXREFREE              1049
#define IDC_FILE_TIM                    1050
#define IDC_LIST_HELP                   1051
#define IDC_LIST_IMAGES                 1052
#define IDC_LIST_PALETTES               1053
#define IDC_MAIN_TAB                    1054
#define IDC_MANLUNTEXT1                 1055
#define IDC_MANLUNTEXT2                 1056
#define IDC_MANUAL_IMAGES               1057
#define IDC_MANUAL_PALETTE              1058
#define IDC_NUM_IMAGES                  1059
#define IDC_NUM_PALETTES                1060
#define IDC_OFFSET_LAB1                 1061
#define IDC_OFFSET_LAB2                 1062
#define IDC_PALETTE_TYPE                1063
#define IDC_PALLAB                      1064
#define IDC_SELBUTTON                   1065
#define IDC_SELBUTTON2                  1066
#define IDC_SELBUTTON3                  1067
#define IDC_SELBUTTON4                  1068
#define IDC_SELBUTTON4B                 1069
#define IDC_SELBUTTON5                  1070
#define IDC_SELBUTTON6                  1071
#define IDC_SELBUTTON7                  1072
#define IDC_SELBUTTON8                  1073
#define IDC_SELBUTTON9                  1074
#define IDC_SELBUTTON10                 1075
#define IDC_SELBUTTON11                 1076
#define IDC_SELBUTTON12                 1077
#define IDC_SHIRT_TEX                   1078
#define IDC_SHIRT_TEXTURE               1079
#define IDC_TEXGIOCTEXT1                1080
#define IDC_CHECK_IMAGEANDPAL           1080
#define IDC_TEXGIOCTEXT2                1081
#define IDC_TITLE_IMAGE                 1082
#define IDC_TITLE_PALETTE               1083
#define IDC_TYPETEXT1                   1084
#define IDC_TYPETEXT2                   1085
#define IDC_VIEWBUTTON2                 1086
#define IDC_VIEWBUTTON5                 1087
#define IDC_VIEWBUTTON6                 1088
#define IDC_VIEWBUTTON8                 1089
#define IDC_VIEWBUTTON11                1090
#define IDC_VIEWBUTTON12                1091
#define IDC_WECOMPRESSOR                1092
#define IDC_WECOMPRESSOR_WENDETTA       1093
#define IDC_XLAB                        1094
#define IDC_XXLAB                       1095
#define IDC_YLAB                        1096
#define IDC_LOGO_CARP                   1097

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        272
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1098
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
